### ISSUE TITLE
[Feat] Adding reverse DNS info to DNS name in NetBox

### ISSUE THREAD

**Issue by Wulfg4r** [lopes/netbox-scanner#17]
Hi,
thank you for the neat script.
Do you think that's possible to add the reverse DNS info discovered by the nmap scan as DNS Name in the host information passed to NetBox?
I'm new with Python and NetBox, so I've not yet tried to do it myself.
And before starting the endeavor, know if at least it's possible could be useful ;-)

Thanks again, regards

- Manuel B.

**Comment by lopes** [comment]
As you may notice, I'm quite busy in another projects and netbox-scanner got out from my priorities. That's why I'm away and the issues are growing here.

Well, I really think that the best way to improve netbox-scanner is to create modules that can retrieve IP and descriptions from trusted sources, like DNS, NetXMS, PRTG, or Cisco Prime. Nmap should be the last option.

This would drive to a 2.0 version of this script, since the code should be changed from its core to the CLI. Of course it'll require time to develop and test, which I don't have now.

José Lopes

**Comment by lopes** [comment]
Create issue #18 with other improvements for new version.
